# Generated by Django 3.1.7 on 2021-02-27 09:11

from django.db import migrations, models
import django_kerberos.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kerberos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kerberosuser',
            managers=[
                ('objects', django_kerberos.models.KerberosUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='kerberosuser',
            name='has_created_principal',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
